// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyIQli-bguJOXVqhd3tja_8CC3m0szcjM',
    appId: '1:54170640784:web:a86a324f4c6520c1b89315',
    messagingSenderId: '54170640784',
    projectId: 'waste-management-app-9fbf8',
    authDomain: 'waste-management-app-9fbf8.firebaseapp.com',
    storageBucket: 'waste-management-app-9fbf8.appspot.com',
    measurementId: 'G-E3GVQWBHHT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWEq-A-g6uOj4IrwPAgKv3dCg43oidHEg',
    appId: '1:54170640784:android:1218712a18ade3a5b89315',
    messagingSenderId: '54170640784',
    projectId: 'waste-management-app-9fbf8',
    storageBucket: 'waste-management-app-9fbf8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaCmnm2-Cd58N-Bu8xrfbktjXK0GF86sg',
    appId: '1:54170640784:ios:3570b7c22592260cb89315',
    messagingSenderId: '54170640784',
    projectId: 'waste-management-app-9fbf8',
    storageBucket: 'waste-management-app-9fbf8.appspot.com',
    androidClientId: '54170640784-rbpq6v01jn0be6b7ohcc01j3c8ncqnj6.apps.googleusercontent.com',
    iosClientId: '54170640784-6v6tt4phmtf2e3jkrd3mhi2u720i76hc.apps.googleusercontent.com',
    iosBundleId: 'com.example.wasteManagemetApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaCmnm2-Cd58N-Bu8xrfbktjXK0GF86sg',
    appId: '1:54170640784:ios:8f32e74bfa2c3162b89315',
    messagingSenderId: '54170640784',
    projectId: 'waste-management-app-9fbf8',
    storageBucket: 'waste-management-app-9fbf8.appspot.com',
    androidClientId: '54170640784-rbpq6v01jn0be6b7ohcc01j3c8ncqnj6.apps.googleusercontent.com',
    iosClientId: '54170640784-h01sf0oiphqc4fb1eti76e2ck6m8d8hc.apps.googleusercontent.com',
    iosBundleId: 'com.example.wasteManagemetApp.RunnerTests',
  );
}
